---

sonarr_name: sonarr
sonarr_image: linuxserver/sonarr
sonarr_ports:
  - 8989:8989
  - 9898:9898
sonarr_config_directory: /opt/sonarr
sonarr_tv_directory: /mnt/media/tv
sonarr_download_directory: /mnt/media/downloads
sonarr_environment_variables:
  PUID: "{{ media_uid }}"
  PGID: "{{ media_gid }}"
  TZ: America/Chicago

sonarr_docker_additional_options:
  restart_policy: unless-stopped

sonarr_config:
  ApiKey: "abc123"
  UrlBase: "example.com"
  LaunchBrowser: "False"
  AnalyticsEnabled: "False"

media_user: mediasvc
media_uid: "1099"
media_group: media
media_gid: "1099"